algo = input('Digite algo: ')
print(' O tipo primitivo desse valor é', type(algo))
print('É um numero? ', algo.isnumeric())
print('É alfabético? ', algo.isalpha())
print('É alfanumérico? ', algo.isalnum())
print('Está em maiúsculas? ', algo.isupper())
print('Está em minúsculas? ', algo.islower())
